import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronRight, ChevronsRight } from 'lucide-react';
import clsx from 'clsx';
import 'katex/dist/katex.min.css';
import { InlineMath, BlockMath } from 'react-katex';

type VisualizationMode = 'open' | 'closed' | 'single-point';

export const BorelIntegration: React.FC = () => {
  const [mode, setMode] = useState<VisualizationMode>('open');
  const [animationStep, setAnimationStep] = useState(0);

  // Auto-reset animation when switching modes
  useEffect(() => {
    setAnimationStep(0);
  }, [mode]);

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 min-h-[600px] flex flex-col md:flex-row gap-8">
      
      {/* Sidebar: Navigation and Explanations */}
      <div className="md:w-1/3 flex flex-col gap-6">
        <div className="space-y-4">
            <h2 className="text-xl font-bold text-gray-800 border-b pb-2">Borel Sets <InlineMath math="\mathcal{B}(\mathbb{R})" /></h2>
            <div className="prose prose-sm text-gray-600 bg-gray-50 p-4 rounded-lg border border-gray-100">
                <p>
                    An important example of a generated $\sigma$-algebra is the class <InlineMath math="\mathcal{B}(\mathbb{R})" /> of <strong>Borel subsets</strong> of <InlineMath math="\mathbb{R}" />:
                </p>
                <BlockMath math="\mathcal{B}(\mathbb{R}) := \sigma\{(a, b] : a, b \in \mathbb{R}, a < b\}" />
                <p className="mt-2 text-xs italic opacity-80">
                    *Note: Whether generated by open intervals <InlineMath math="(a, b)" /> or semi-open <InlineMath math="(a, b]" />, the resulting <InlineMath math="\sigma" />-algebra is the same.
                </p>
                <p className="mt-2">
                    All "reasonable" subsets of <InlineMath math="\mathbb{R}" /> are Borel, but <InlineMath math="\mathcal{B}(\mathbb{R}) \neq \mathcal{P}(\mathbb{R})" />.
                </p>
            </div>

            <div className="flex flex-col gap-2">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Visualization Modes</p>
                <ModeButton 
                    active={mode === 'open'} 
                    onClick={() => setMode('open')}
                    label="1. Open Intervals" 
                    math="(a, b)"
                />
                <ModeButton 
                    active={mode === 'closed'} 
                    onClick={() => setMode('closed')}
                    label="2. Closed Sets" 
                    math="[a, b] = (a, b)^c"
                />
                <ModeButton 
                    active={mode === 'single-point'} 
                    onClick={() => setMode('single-point')}
                    label="3. Single Points" 
                    math="\{x\} = \bigcap (x - \epsilon, x + \epsilon)"
                />
            </div>
        </div>

        <div className="mt-auto space-y-4 pt-4 border-t">
            <h4 className="font-bold text-gray-700 text-sm">Multivariate Extension</h4>
            <div className="text-xs text-gray-600 bg-gray-50 p-3 rounded border">
                <BlockMath math="\mathcal{B}(\mathbb{R}^m) := \sigma \left\{ \prod_{i=1}^{m} (a_i, b_i] \right\}" />
                <p className="mt-2">
                    Start with "bricks" (products of intervals) to generate Borel sets in higher dimensions.
                </p>
            </div>
             <h4 className="font-bold text-gray-700 text-sm">Trace $\sigma$-algebra</h4>
            <div className="text-xs text-gray-600 bg-gray-50 p-3 rounded border">
                For a subset <InlineMath math="\Omega \subset \mathbb{R}^m" />, the trace is:
                <BlockMath math="\mathcal{F} = \{ \Omega \cap A : A \in \mathcal{B}(\mathbb{R}^m) \}" />
            </div>
        </div>
      </div>

      {/* Main: Visualization Area */}
      <div className="md:w-2/3 flex flex-col items-center justify-center relative bg-slate-50 rounded-xl border-2 border-dashed border-gray-200 p-8 overflow-hidden min-h-[400px]">
        
        <h2 className="text-xl font-bold text-gray-700 mb-12 w-full text-center">
             {mode === 'open' && <>Open Interval <InlineMath math="(a, b)" /></>}
             {mode === 'closed' && <>Closed Set <InlineMath math="[a, b]" /> via Complement</>}
             {mode === 'single-point' && <>Single Point <InlineMath math="\{x\}" /> via Intersection</>}
        </h2>

        <div className="number-line-container relative w-full h-32 flex items-center justify-center">
            {/* Base Line */}
            <div className="absolute w-[90%] h-1 bg-gray-300 rounded-full" />
            
            {/* Ticks */}
            <div className="absolute w-[90%] flex justify-between text-xs text-gray-400 -bottom-8 font-mono">
                <span><InlineMath math="-\infty" /></span>
                <span>0</span>
                <span>1</span>
                <span><InlineMath math="+\infty" /></span>
            </div>

            <AnimatePresence mode='wait'>
                {mode === 'open' && (
                <motion.div 
                    initial={{ scaleX: 0, opacity: 0 }}
                    animate={{ scaleX: 1, opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="absolute h-10 bg-blue-500/20 border-x-2 border-blue-600 w-1/3 flex items-center justify-center group cursor-help"
                >
                    <div className="absolute -top-8 text-blue-700 font-bold bg-white px-2 rounded shadow-sm opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-10">
                        <InlineMath math="(a, b) = \{ x : a < x < b \}" />
                    </div>
                    <span className="text-blue-800 font-bold text-sm"><InlineMath math="(a, b)" /></span>
                </motion.div>
                )}

                {mode === 'closed' && (
                    <motion.div className="w-full h-full absolute flex items-center justify-center">
                        {animationStep === 0 ? (
                             <motion.div 
                                key="complement-base"
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                className="absolute w-[95%] h-10 bg-green-500/10 border-t border-b border-green-200 flex items-center justify-center"
                            >
                                <span className="absolute -top-8 text-green-700 font-bold"><InlineMath math="\mathbb{R}" /> (Whole Space)</span>
                                {/* Hole */}
                                <div className="h-full bg-slate-50 w-1/3 border-x-2 border-dashed border-gray-400 absolute flex items-center justify-center">
                                    <span className="text-xs text-gray-400">Exclude <InlineMath math="(a, b)" /></span>
                                </div>
                            </motion.div>
                        ) : (
                            <motion.div 
                                key="closed-result"
                                initial={{ scaleX: 0.8, opacity: 0 }}
                                animate={{ scaleX: 1, opacity: 1 }}
                                className="absolute w-1/3 h-10 bg-blue-600/20 border-x-4 border-blue-800 flex items-center justify-center"
                            >
                                <span className="text-blue-900 font-bold text-sm"><InlineMath math="[a, b]" /></span>
                                <div className="absolute -bottom-8 text-blue-800 text-xs font-medium bg-white px-2 py-1 rounded shadow-sm">
                                    Remainder is Closed
                                </div>
                            </motion.div>
                        )}
                    </motion.div>
                )}

                {mode === 'single-point' && (
                    <div className="absolute inset-0 flex items-center justify-center">
                         <motion.div
                            className="h-10 bg-orange-500/30 border-x-2 border-orange-600 flex items-center justify-center absolute"
                            animate={{ 
                                width: `${30 / (animationStep + 1)}%`
                            }}
                            transition={{ type: "spring", stiffness: 120, damping: 20 }}
                        >
                            <span className="text-orange-900 font-bold text-xs -translate-y-10 whitespace-nowrap bg-white/80 px-1 rounded backdrop-blur-sm">
                                <InlineMath math={`(x - \\frac{1}{${animationStep+1}}, x + \\frac{1}{${animationStep+1}})`} />
                            </span>
                        </motion.div>
                        <div className="w-2 h-2 bg-black rounded-full z-10" />
                        <span className="absolute mt-10 font-serif font-bold italic">x</span>
                    </div>
                )}
            </AnimatePresence>
        </div>

        <div className="flex gap-4 min-h-[60px] mt-8 items-center justify-center w-full">
             {mode === 'single-point' && (
                 <button 
                  onClick={() => setAnimationStep(s => (s + 1) % 5)}
                  className="px-6 py-3 bg-indigo-600 text-white rounded-lg shadow-lg hover:bg-indigo-700 transition-all active:scale-95 flex items-center gap-2 font-medium"
                 >
                   Shrink Interval (n={animationStep+1}) <ChevronRight size={18}/>
                 </button>
             )}
             {mode === 'closed' && (
                 <button 
                  onClick={() => setAnimationStep(s => s === 0 ? 1 : 0)}
                  className="px-6 py-3 bg-indigo-600 text-white rounded-lg shadow-lg hover:bg-indigo-700 transition-all active:scale-95 flex items-center gap-2 font-medium"
                 >
                   {animationStep === 0 ? "Take Complement" : "Reset"} <ChevronsRight size={18}/>
                 </button>
             )}
        </div>

      </div>
    </div>
  );
};

const ModeButton = ({ active, onClick, label, math }: any) => (
  <button
    onClick={onClick}
    className={clsx(
      "text-left p-3 rounded-lg border transition-all w-full group",
      active 
        ? "bg-white border-blue-500 shadow-md ring-1 ring-blue-200" 
        : "bg-white border-transparent hover:bg-gray-100 hover:border-gray-200"
    )}
  >
    <div className={clsx("font-bold text-sm", active ? "text-blue-700" : "text-gray-700")}>{label}</div>
    <div className="text-sm text-gray-500 mt-1 font-normal opacity-80 group-hover:opacity-100 transition-opacity">
        <InlineMath math={math} />
    </div>
  </button>
);
